# Generated by Django 3.2.3 on 2021-05-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('optionA', models.TextField()),
                ('optionB', models.TextField()),
                ('optionC', models.TextField()),
                ('optionD', models.TextField()),
                ('correctOption', models.CharField(max_length=1)),
                ('tag', models.TextField()),
            ],
        ),
    ]
