# Generated by Django 3.2.3 on 2021-05-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
