# Generated by Django 3.2.3 on 2021-05-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0002_rename_questions_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correctOption',
            field=models.TextField(),
        ),
    ]
