# Generated by Django 2.2.1 on 2021-05-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='email',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='username',
            field=models.CharField(max_length=10),
        ),
    ]
