# Generated by Django 3.2.3 on 2021-05-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
