# Generated by Django 2.2.1 on 2021-05-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210526_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
