# Generated by Django 2.2.1 on 2021-05-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210526_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='idd',
            field=models.UUIDField(default='SOME STRING'),
        ),
    ]
