# Generated by Django 2.2.1 on 2021-05-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_recruiter_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='idd',
            field=models.CharField(max_length=20),
        ),
    ]
