# Generated by Django 2.2.1 on 2021-05-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210526_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='idd',
        ),
        migrations.AddField(
            model_name='recruiter',
            name='title',
            field=models.UUIDField(default='SOME STRING'),
        ),
    ]
