# Generated by Django 2.2.1 on 2021-05-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20210526_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='title',
            field=models.UUIDField(default=''),
        ),
    ]
