# Generated by Django 2.2.1 on 2021-05-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20210526_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='title',
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='email',
            field=models.EmailField(max_length=20),
        ),
    ]
