# Generated by Django 3.2.3 on 2021-05-25 12:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUUIDModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('DOB', models.DateField()),
                ('phone', models.CharField(max_length=11)),
                ('StreetAddress', models.TextField()),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('pincode', models.IntegerField()),
                ('highestDegree', models.CharField(max_length=20)),
                ('yearOfDegreeCompleted', models.IntegerField()),
                ('institution', models.TextField()),
                ('specification', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentPortal.myuuidmodel')),
            ],
        ),
    ]
