# Generated by Django 3.2.3 on 2021-05-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentPortal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='MyUUIDModel',
        ),
    ]
