# Generated by Django 3.2.3 on 2021-05-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentPortal', '0006_analysis_detailed_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
